export const GET_CINEMAS = 'GET_CINEMAS';
export const CHANGE_CURR_CINEMA = 'CHANGE_CURRENT_CINEMA';
export const CHANGE_CURR_MOVIES = 'CHANGE_CURRENT_MOVIES';
export const CHANGE_CURR_MOVIE = 'CHANGE_CURRNET_MOVIE';
export const GET_MOVIES = 'GET_MOVIES';
export const GET_UPCOMING = 'GET_UPCOMING';
export const CHANGE_UPCOMING_MOVIE = 'CHANGE_UPCOMING_MOVIE';